# .github/workflows/ci-pipeline.yml

name: Python CI Pipeline

# Trigger: Chạy workflow này mỗi khi có push hoặc pull request vào nhánh `main`
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Môi trường chạy: Sử dụng phiên bản macOS mới nhất do GitHub cung cấp
    runs-on: macos-latest

    steps:
      # Bước 1: Checkout code từ kho chứa về máy ảo
      - name: Check out repository code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Bước 3: Cài đặt các thư viện cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Kiểm tra chất lượng code với flake8
      # Lệnh này sẽ kiểm tra code trong toàn bộ dự án
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Bước 5: Chạy các bài test với pytest
      - name: Test with pytest
        run: |
          pytest